imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                user: db_user
                password: db_password
                path: %kernel.cache_dir%/test.db
                charset: utf8

parameters:
    clipper.brands: Tests/Resources/terms/test_brands.xml
    clipper.conditions: Tests/Resources/terms/test_conditions.xml

    fwsso_baseurl: http://alexysh.fwsso.pslgroup.com/ssoapi
    fwsso_api:
        url: http://alexysh.fwsso.pslgroup.com/ssoapi
        app_token: ac1e9d98889fb2955c74ba4a03e47d45874d21e729c07133815bff259ac74510
