psl_clipper:
    resource: "@PSLClipperBundle/Resources/config/routing.yml"
    prefix:   /clipper

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /clipper/api/doc
