psl_clipper:
    resource: "@PSLClipperBundle/Resources/config/routing.yml"
    prefix:   /clipper

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc