# FirstQProject.orm.yml
PSL\ClipperBundle\Entity\FirstQProject:
  type: entity
  table: firstq_project
  repositoryClass: PSL\ClipperBundle\Entity\Repository\FirstQProjectRepository
  indexes:
    id_index:
      columns: [ id ]
  id:
    id:
      type: guid
      generator:
        strategy: UUID
  fields:
    # definition of fields
    bc_order_id:
      type: string
      length: 200
      nullable: true
      options:
        comment: Bigcommerce order id
    bc_product_id:
      type: string
      length: 200
      options:
        comment: id of the Bigcommerce product
    form_data_raw:
      type: text
      options:
        comment: result of the form submission, as json or as associative array serialized
    sheet_data_raw:
      type: text
      options:
        comment: result of the Google Spreadsheet as json or as associative array serialized
    limesurvey_data_raw:
      type: text
      nullable: true
      options:
        comment: LimeSurvey raw data as associative array serialized
    state:
      type: string
      length: 100
      options:
        comment: last error or success code. Use to keep track of the request
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
      options:
        comment: date and time at creation
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
      options:
        comment: date and time at update
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
