# FirstQProject.orm.yml
PSL\ClipperBundle\Entity\FirstQProject:
  type: entity
  table: firstq_project
  repositoryClass: PSL\ClipperBundle\Entity\Repository\FirstQProjectRepository
  indexes:
    id_index:
      columns: [ id ]
  id:
    id:
      type: guid
      generator:
        strategy: UUID
  fields:
    # definition of fields
    # user_id:
      # type: string
      # nullable: true
      # length: 200
      # options:
        # comment: id of the user
    # order_id:
      # type: string
      # nullable: true
      # length: 200
      # options:
        # comment: id of the order
    # form_data_raw:
      # type: text
      # options:
        # comment: result of the form submission, as json or as associative array serialized
    group_uuid:
      type: guid
      options:
        comment: id of the group this FirstQ Project is associated with
    sheet_data_raw:
      type: text
      options:
        comment: result of the Google Spreadsheet as json or as associative array serialized
    limesurvey_data_raw:
      type: text
      nullable: true
      options:
        comment: LimeSurvey raw data as associative array serialized
    state:
      type: string
      length: 100
      options:
        comment: last error or success code. Use to keep track of the request
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
      options:
        comment: date and time at creation
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
      options:
        comment: date and time at update
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
