# FirstQGroup.orm.yml
PSL\ClipperBundle\Entity\FirstQGroup:
  type: entity
  table: firstq_group
  repositoryClass: PSL\ClipperBundle\Entity\Repository\FirstQProjectRepository
  indexes:
    id_index:
      columns: [ id ]
  id:
    id:
      type: guid
      generator:
        strategy: UUID
  fields:
    userId:
      type: string
      length: 200
      column: user_id
      nullable: true
      options:
        comment: id of the user
    orderId:
      type: string
      length: 200
      column: order_id
      nullable: true
      options:
        comment: id of the order
    formDataRaw:
      type: text
      column: form_data_raw
      options:
        comment: result of the form submission, as json or as associative array serialized
    state:
      type: string
      length: 100
      options:
        comment: last error or success code. Use to keep track of the request
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
      options:
        comment: date and time at creation
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
      options:
        comment: date and time at update
  oneToMany:
    projects:
      targetEntity: FirstQProject
      mappedBy: group_uuid
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
