# LimeSurveyResponse.orm.yml
PSL\ClipperBundle\Entity\LimeSurveyResponse:
  type: entity
  table: limesurvey_responses
  repositoryClass: PSL\ClipperBundle\Entity\Repository\LimeSurveyResponseRepository
  indexes:
    id_index:
      columns: [ ls_token ]
  id:
    ls_token:
      type: string
      length: 255
      column: ls_token
      options:
        comment: LimeSurvey token
  manyToOne:
    firstqgroup:
      targetEntity: FirstQGroup
      cascade: ["remove"]
      fetch: "EXTRA_LAZY"
      joinColumn:
        name: firstqgroup_id
        referencedColumnName: id
    firstqproject:
      targetEntity: FirstQProject
      cascade: ["remove"]
      fetch: "EXTRA_LAZY"
      joinColumn:
        name: firstqproject_id
        referencedColumnName: id
  fields:
    member_id:
      type: integer
      column: member_id
      options:
        comment: MDM member id
    response_raw:
      type: text
      column: response_raw
      options:
        comment: Exported response from LimeSurvey, base64 encoded
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
      options:
        comment: date and time at creation
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
      options:
        comment: date and time at update
  lifecycleCallbacks:
    preUpdate: [ setUpdatedValue ]
