<?php

namespace PSL\ClipperBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Collections\Criteria;

// custom
use PSL\ClipperBundle\Entity\FirstQProject;

/**
 * FirstQProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstQProjectRepository extends EntityRepository
{
  public function findByIdsAndState($ids = array(), $state)
  {
    $expr = Criteria::expr();
    $criteria = Criteria::create();
    $criteria->where($expr->in('bc_product_id', $ids));
    $criteria->andWhere($expr->eq('state', $state));
    
    return $this->matching($criteria);
  }
  
  public function findByState($state)
  {
    $expr = Criteria::expr();
    $criteria = Criteria::create();
    $criteria->where($expr->eq('state', $state));
    
    return $this->matching($criteria);
  }
}
