<?php

namespace PSL\ClipperBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LimeSurveyResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimeSurveyResponseRepository extends EntityRepository
{
  
}
