# /src/PSL/ClipperBundle/Resources/config/config.yml

#
# Semantic Configuration: Don't Do It¶
# http://symfony.com/doc/current/best_practices/configuration.html#semantic-configuration-don-t-do-it
# test
 
