# PSL/ClipperBundle/Resources/config/config.yml

# GremoBuzzBundle Configuration
gremo_buzz:
  client: "native" # allowed "curl", "multi_curl" or "native"
  options:
    ignore_errors: true
    max_redirects: 5
    timeout: 5
    verify_peer: true
 
# Nelmio CORS
nelmio_cors:
  paths:
    '^/clipper/api':
      allow_credentials: true
      allow_origin: ['*']
      allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
      allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
      expose_headers: []
      max_age: 3600
