psl_clipper_limesurvey_redirect:
  path:     /limesurvey/{sid}/{slug}/{lang}
  defaults: { _controller: PSLClipperBundle:Clipper:redirectLimeSurvey }
  requirements:
    sid: \d+
    
# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /api

clipper_user:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperUserController
  prefix:   /api

api_login_check:
   path:    /api/login_check

api_login_admin_check:
    path:   /api/admin/login_check

clipper_user:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperUserController
  prefix:   /ws

api_login_check:
   path: /ws/login_check

psl_clipper_debug:
  path:     /debug
  defaults: { _controller: PSLClipperBundle:Clipper:debug }

psl_clipper_exit:
  path:     /limesurvey/exit
  defaults: { _controller: PSLClipperBundle:Clipper:exit }

psl_clipper_thankyou:
  path:     /thankyou/{fquuid}
  defaults: { _controller: PSLClipperBundle:Clipper:thankyou }
