# psl_clipper_homepage:
    # path:     /hello/{name}
    # defaults: { _controller: PSLClipperBundle:Default:index }

# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /ws
