psl_clipper_limesurvey_redirect:
  path:     /limesurvey/{sid}/{slug}/{lang}
  defaults: { _controller: PSLClipperBundle:Clipper:redirectLimeSurvey }
  requirements:
    sid: \d+
    
psl_clipper_debug:
  path:     /debug
  defaults: { _controller: PSLClipperBundle:Clipper:debug }

psl_clipper_exit:
  path:     /limesurvey/exit
  defaults: { _controller: PSLClipperBundle:Clipper:exit }

psl_clipper_chart:
  path:     /api/charts
  defaults: { _controller: PSLClipperBundle:Charts:charts }

psl_clipper_thankyou:
  path:     /thankyou/{fquuid}
  defaults: { _controller: PSLClipperBundle:Clipper:thankyou }

# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /ws