psl_clipper_limesurvey_redirect:
  path:     /limesurvey/{sid}/{slug}/{lang}
  defaults: { _controller: PSLClipperBundle:Clipper:redirectLimeSurvey }
  requirements:
    sid: \d+

# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /ws

psl_clipper_debug:
  path:     /debug
  defaults: { _controller: PSLClipperBundle:Clipper:debug }
