# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /ws

psl_clipper_debug:
  path:     /debug
  defaults: { _controller: PSLClipperBundle:Clipper:debug }
