psl_clipper_limesurvey_redirect:
  path:     /limesurvey/{sid}/{slug}
  defaults: { _controller: PSLClipperBundle:Clipper:redirectLimeSurvey }
  requirements:
    sid: \d+

# Automatic routes
clipper:
  type:     rest
  resource: PSL\ClipperBundle\Controller\ClipperController
  prefix:   /ws

psl_clipper_googlespreadsheets_feasibility:
  path:     /clipper-gs/feasibility/{loi}/{ir}/{country}/{specialty}
  defaults: { _controller: PSLClipperBundle:GoogleSpreadsheet:requestFeasibility }

psl_clipper_googlespreadsheets_universes:
  path:     /clipper-gs/universes/{country}/{specialty}
  defaults: { _controller: PSLClipperBundle:GoogleSpreadsheet:requestUniverses }
