services:
  
  google_spreadsheet:
    class: PSL\ClipperBundle\Service\GoogleSpreadsheetService
    arguments: [%google_spreadsheets%]
  
  survey_builder:
    class: PSL\ClipperBundle\Service\SurveyBuilderService
    # @TODO: only get templating
    arguments: [@service_container]
    # arguments: [@templating]
    # calls:
      # - [setTemplating, ["@templating"]]
      
  # nps_plus_survey:
    # class: PSL\ClipperBundle\Survey\NPSPlusSurvey
    # calls:
      # - [setParentTemplating, ["@templating"]]
