services:
  
  google_spreadsheet:
    class: PSL\ClipperBundle\Service\GoogleSpreadsheetService
    arguments: [%google_spreadsheets%]
  
  rpanel:
    class: PSL\ClipperBundle\Service\RPanelService
    arguments: [%rpanel%]
  
  survey_builder:
    class: PSL\ClipperBundle\Service\SurveyBuilderService
    # @TODO: only get templating
    arguments: [@service_container]
      
  limesurvey:
    class: PSL\ClipperBundle\Utils\LimeSurvey
  
  explode_tree:
    class: PSL\ClipperBundle\Utils\ExplodeTree
  
  survey_chart_map:
    class: PSL\ClipperBundle\Charts\SurveyChartMap
  
  chart_assembler:
    class: PSL\ClipperBundle\Charts\Assembler
    arguments: [@service_container]
  
  clipper_serializer:
    class: PSL\ClipperBundle\Utils\ClipperSerializer
    
    
   
  # --------------------------- #
  #   Clipper event listeners   #
  # --------------------------- #
  
  # Listeners are called in descending order by priority. Highest priority is called first.

  clipper.listener.order_complete:
    class: PSL\ClipperBundle\Listener\LimeSurveyPending
    arguments: ["@service_container", "limesurvey_pending"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 100 }
      
  clipper.listener.limesurvey_created:
    class: PSL\ClipperBundle\Listener\LimeSurveyCreated
    arguments: ["@service_container", "limesurvey_created"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 90 }
      
  clipper.listener.rpanel_complete:
    class: PSL\ClipperBundle\Listener\RpanelComplete
    arguments: ["@service_container", "rpanel_complete"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 80 }
      
  clipper.listener.limesurvey_complete:
    class: PSL\ClipperBundle\Listener\LimeSurveyComplete
    arguments: ["@service_container", "limesurvey_complete"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 70 }
  
  # refresh responses
  clipper.listener.limesurvey_responses:
    class: PSL\ClipperBundle\Listener\LimeSurveyResponses
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: ls_refresh_responses, method: refreshResponses, priority: 0 }
      - { name: kernel.event_listener, event: after_limesurvey_complete, method: refreshResponses, priority: 0 }
  
  # types of charts
  clipper.chart.net_promoters:
    class: PSL\ClipperBundle\Charts\Types\NetPromoters
    arguments: ["@service_container", "net_promoters"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
