services:
  
  google_spreadsheet:
    class: PSL\ClipperBundle\Controller\GoogleSpreadsheetService
    arguments: [%google_spreadsheets%]
  
  survey_builder:
    class: PSL\ClipperBundle\Controller\SurveyBuilderService
