services:
  clipper_cache:
    class: PP\SampleBundle\Service\ClipperCacheService
    arguments:
      - %clipper_cache.config%
      - @service_container

  google_spreadsheet:
    class: PP\SampleBundle\Service\GoogleSpreadsheetService
    arguments:
      - @service_container
      - %google_spreadsheets.client_id%
      - %google_spreadsheets.service_account_name%
      - %google_spreadsheets.p12_file_name%
      - %google_spreadsheets.spreadsheet_name%
      - %google_spreadsheets.worksheet_name%
      - %google_spreadsheets.p12_file_path%

  rpanel:
    class: PP\SampleBundle\Service\RPanelService
    arguments: [%rpanel%]

  survey_builder:
    class: PP\SampleBundle\Service\SurveyBuilderService
    arguments: [@service_container]

  limesurvey:
    class: PP\SampleBundle\Utils\LimeSurvey
    arguments:
      - %limesurvey.api.ls_baseurl%
      - %limesurvey.api.ls_user%
      - %limesurvey.api.ls_password%

  explode_tree:
    class: PP\SampleBundle\Utils\ExplodeTree

  quota_map:
    class: PP\SampleBundle\Utils\Quota

  survey_chart_map:
    class: PP\SampleBundle\Charts\SurveyChartMap

  chart_assembler:
    class: PP\SampleBundle\Charts\Assembler
    arguments: [@service_container]

  chart_helper:
    class: PP\SampleBundle\Service\ClipperChartsService
    arguments: [@service_container]

  download_assembler:
    class: PP\SampleBundle\Downloads\Assembler
    arguments: [@service_container]

  clipper_serializer:
    class: PP\SampleBundle\Utils\ClipperSerializer

  yaml_admin_user_provider:
    class: PP\SampleBundle\Security\User\YamlAdminUserProvider
    arguments: ["%kernel.root_dir%/Resources/users.yml"]

  fw_sso_user_provider:
    class: PP\SampleBundle\Security\User\FWSSOUserProvider
    arguments: [@service_container, "%kernel.root_dir%/Resources/invoice_whitelist.yml"]

  fw_sso_quick_login_user_provider:
    class: PP\SampleBundle\Security\User\FWSSOQuickLoginUserProvider
    arguments: [@service_container, "%kernel.root_dir%/Resources/invoice_whitelist.yml"]

  fw_sso_webservice:
    class: PP\SampleBundle\Service\FWSSOWebservice

  drupal_password_encoder:
    class: PP\SampleBundle\Service\DrupalPasswordEncoder
    arguments: [@service_container]

  translator_service:
    class: PP\SampleBundle\Service\TranslatorService
    arguments: [@service_container]

  user_service:
    class: PP\SampleBundle\Service\UserService
    arguments: [@service_container]

  geo_mapper:
    class: PP\SampleBundle\Utils\GeoMapper

  # -------------------------------- #
  #   Clipper FQ process listeners   #
  # -------------------------------- #

  # Listeners are called in descending order by priority. Highest priority is called first.

  clipper.listener.limesurvey_pending:
    class: PP\SampleBundle\Listener\LimeSurveyPending
    arguments: [@service_container, "limesurvey_pending"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 100 }

  clipper.listener.limesurvey_addparticipants:
    class: PP\SampleBundle\Listener\LimeSurveyAddParticipants
    arguments: [@service_container, "limesurvey_addparticipants"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 96 }

  clipper.listener.limesurvey_setrawdata:
    class: PP\SampleBundle\Listener\LimeSurveySetRawData
    arguments: [@service_container, "limesurvey_setrawdata"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 93 }

  clipper.listener.limesurvey_created:
    class: PP\SampleBundle\Listener\LimeSurveyCreated
    arguments: [@service_container, "limesurvey_created", "@rpanel"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 90 }

  clipper.listener.rpanel_complete:
    class: PP\SampleBundle\Listener\RpanelComplete
    arguments: [@service_container, "rpanel_complete"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 80 }

  clipper.listener.limesurvey_complete:
    class: PP\SampleBundle\Listener\LimeSurveyComplete
    arguments: [@service_container, "limesurvey_complete"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 70 }

  clipper.listener.limesurvey_exported:
    class: PP\SampleBundle\Listener\LimeSurveyExported
    arguments: [@service_container, "limesurvey_exported"]
    tags:
      - { name: kernel.event_listener, event: fq_process, method: onMain, priority: 60 }

  # refresh responses
  clipper.listener.limesurvey_responses:
    class: PP\SampleBundle\Listener\LimeSurveyResponses
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: ls_refresh_responses, method: refreshResponses, priority: 0 }
      - { name: kernel.event_listener, event: after_limesurvey_complete, method: refreshResponses, priority: 0 }

  # Limesurvey Translator
  clipper.limesurvey.translator:
    class: PP\SampleBundle\Listener\LimeSurveyTranslator
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: limesurvey_translation, method: onTranslate, priority: 0 }

  # ------------------------------ #
  #   Clipper Charts listeners     #
  # ------------------------------ #

  #NPS: 001
  clipper.chart.nps:
    class: PP\SampleBundle\Charts\Types\NPS
    arguments: [@service_container, "NPS"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 002
  clipper.chart.loyalty:
    class: PP\SampleBundle\Charts\Types\Loyalty
    arguments: [@service_container, "Loyalty"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 003
  clipper.chart.doctorspromote:
    class: PP\SampleBundle\Charts\Types\DoctorsPromote
    arguments: [@service_container, "DoctorsPromote"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 004
  clipper.chart.promoterspromote:
    class: PP\SampleBundle\Charts\Types\PromotersPromote
    arguments: [@service_container, "PromotersPromote"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 005
  clipper.chart.detractorspromote:
    class: PP\SampleBundle\Charts\Types\DetractorsPromote
    arguments: [@service_container, "DetractorsPromote"]
    tags:
      - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 006
  clipper.chart.promvsdetrpromote:
    class: PP\SampleBundle\Charts\Types\PromVsDetrPromote
    arguments: [@service_container, "PromVsDetrPromote"]
    tags:
       - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 007
  clipper.chart.ppdbrandmessages:
    class: PP\SampleBundle\Charts\Types\PPDBrandMessages
    arguments: [@service_container, "PPDBrandMessages"]
    tags:
       - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #NPS: 008
  clipper.chart.dna:
    class: PP\SampleBundle\Charts\Types\DNA
    arguments: [@service_container, "DNA"]
    tags:
       - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #Extra for export
  #Table 4
  clipper.chart.promoterspromotemean:
    class: PP\SampleBundle\Charts\Types\PromotersPromoteMean
    arguments: [@service_container, "PromotersPromoteMean"]
    tags:
       - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }
  #Table 9-16
  clipper.chart.ppdbrandmessagesbybrands:
    class: PP\SampleBundle\Charts\Types\PPDBrandMessagesByBrands
    arguments: [@service_container, "PPDBrandMessagesByBrands"]
    tags:
       - { name: kernel.event_listener, event: chart_process, method: onDataTable, priority: 0 }

  # ------------------------------ #
  #   Clipper Download listeners   #
  # ------------------------------ #

  #@TODO: remove this
  clipper.download.nps_plus_dev:
    class: PP\SampleBundle\Downloads\Types\NPSPlusDev
    arguments: [@service_container, "nps_plus", "dev"]
    tags:
       - { name: kernel.event_listener, event: download_process, method: onDownload, priority: 0 }

  clipper.download.nps_plus_excel:
    class: PP\SampleBundle\Downloads\Types\NPSPlusExcel
    arguments: [@service_container, "nps_plus", "xls"]
    tags:
       - { name: kernel.event_listener, event: download_process, method: onDownload, priority: 0 }

  # --------------------------- #
  #   Charts PDF listeners      #
  # --------------------------- #

  clipper.charts.pdf.nps_plus:
    class: PP\SampleBundle\Charts\Pdf\Types\NpsPlusPdf
    arguments: [@service_container, "nps_plus"]
    tags:
       - { name: kernel.event_listener, event: chart_pdf, method: onPdf, priority: 0 }
  clipper.charts.pdf.nps_plus_prev:
    class: PP\SampleBundle\Charts\Pdf\Types\NpsPlusPdf
    arguments: [@service_container, "nps_plus"]
    tags:
       - { name: kernel.event_listener, event: chart_pdf_preview, method: onPdf, priority: 0 }
