<?php

namespace PP\SampleBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Collections\Criteria;

// custom
use PP\SampleBundle\Entity\FirstQProject as FirstQProject;
use PP\SampleBundle\Entity\FirstQGroup as FirstQGroup;

/**
 * FirstQProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstQProjectRepository extends EntityRepository
{
  public function findByState($state)
  {
    $expr = Criteria::expr();
    $criteria = Criteria::create();
    $criteria->where($expr->eq('state', $state));
    
    return $this->matching($criteria);
  }
  
  public function findByStateNot($state)
  {
    $expr = Criteria::expr();
    $criteria = Criteria::create();
    $criteria->where($expr->neq('state', $state));
    
    return $this->matching($criteria);
  }
  
  public function findByFirstqgroupAndNotState(FirstQGroup $fqg, $state)
  {
    $expr = Criteria::expr();
    $criteria = Criteria::create();
    $criteria->where($expr->eq('firstqgroup_id', $fqg->getId()));
    $criteria->where($expr->neq('state', $state));
    
    return $this->matching($criteria);
  }
  
}
