<?php

namespace PP\SampleBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\ArrayCollection;


// custom
use PP\SampleBundle\Entity\FirstQProject;
use PP\SampleBundle\Entity\FirstQGroup;
use PP\SampleBundle\Entity\LimeSurveyResponse;

/**
 * LimeSurveyResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimeSurveyResponseRepository extends EntityRepository
{
  
}
